.\" Process this file with
.\" groff -man -Tascii pcmanfm.1
.\"
.TH PCManFM 1 "February 2006" Linux "User Manuals"
.SH NAME
PCManFM \- A gtk2 based file manager for X Window.
.SH SYNOPSIS
.B pcmanfm
.SH DESCRIPTION
This manual page documents briefly the
.BR PCManFM
file manager.
This manual page was written for the Debian GNU/Linux distribution
(but may be used by others), because the original program does not
have a manual page.
.PP
.B PCManFM
,PCMan File Manager, is an extremly fast and lightweight file manager which features tabbed browsing and user-friendly interface.
Features:
  * Extremly fast and lightweight
  * Can be started in one second on normal machine
  * Tabbed browsing (Similiar to Firefox)
  * Drag & Drop support
  * Files can be dragged among tabs
  * Load large directories in reasonable time
  * File association support (Default application)
  * Basic thumbnail support
  * Bookmarks support
  * Handles non-UTF-8 encoded filenames correctly
  * Provide icon view and detailed list view
  * Standard compliant (Follows FreeDesktop.org)
  * Clean and user-friendly interface (GTK+ 2)
.SH FILES
.I ~/.pcmanfm/bookmarks
: stores your bookmarks.
.br
.I ~/.pcmanfm/main
: stores your preferences.
.br
.I ~/.pcmanfm/mime_info
: stores your mime infomations.
.br
.SH AUTHOR
This manual page was written by Tetralet <tetralet@debian.org.tw>
for the Debian GNU/Linux system.
