/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "app-chooser-dialog.h"
#include "app-chooser-dialog-ui.h"
#include "glade-support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_app_chooser_dlg (void)
{
  GtkWidget *app_chooser_dlg;
  GtkWidget *dialog_vbox;
  GtkWidget *hbox5;
  GtkWidget *label7;
  GtkWidget *file_type;
  GtkWidget *label4;
  GtkWidget *notebook;
  GtkWidget *scrolledwindow1;
  GtkWidget *recommended_apps;
  GtkWidget *label3;
  GtkWidget *scrolledwindow2;
  GtkWidget *all_apps;
  GtkWidget *label2;
  GtkWidget *hbox1;
  GtkWidget *label5;
  GtkWidget *cmdline;
  GtkWidget *browse_btn;
  GtkWidget *alignment1;
  GtkWidget *hbox3;
  GtkWidget *image1;
  GtkWidget *label6;
  GtkWidget *hbox2;
  GtkWidget *open_in_terminal;
  GtkWidget *set_default;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton;
  GtkWidget *okbutton;

  app_chooser_dlg = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (app_chooser_dlg), _("Choose an Application"));
  gtk_window_set_default_size (GTK_WINDOW (app_chooser_dlg), -1, 420);
  gtk_window_set_type_hint (GTK_WINDOW (app_chooser_dlg), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox = GTK_DIALOG (app_chooser_dlg)->vbox;
  gtk_widget_show (dialog_vbox);

  hbox5 = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (dialog_vbox), hbox5, FALSE, TRUE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (hbox5), 2);

  label7 = gtk_label_new (_("File Type To be Opened:"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox5), label7, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label7), 2, 2);

  file_type = gtk_label_new ("");
  gtk_widget_show (file_type);
  gtk_box_pack_start (GTK_BOX (hbox5), file_type, FALSE, FALSE, 0);

  label4 = gtk_label_new (_("Please choose an application from following lists or enter the command line by hand:"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox), label4, FALSE, FALSE, 1);
  gtk_label_set_line_wrap (GTK_LABEL (label4), TRUE);
  gtk_misc_set_padding (GTK_MISC (label4), 4, 4);

  notebook = gtk_notebook_new ();
  gtk_widget_show (notebook);
  gtk_box_pack_start (GTK_BOX (dialog_vbox), notebook, TRUE, TRUE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (notebook), scrolledwindow1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  recommended_apps = gtk_tree_view_new ();
  gtk_widget_show (recommended_apps);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), recommended_apps);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (recommended_apps), FALSE);

  label3 = gtk_label_new_with_mnemonic (_("_Recommended Applications"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 0), label3);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (notebook), scrolledwindow2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  all_apps = gtk_tree_view_new ();
  gtk_widget_show (all_apps);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), all_apps);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (all_apps), FALSE);

  label2 = gtk_label_new_with_mnemonic (_("_All Applications"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 1), label2);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox), hbox1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 4);

  label5 = gtk_label_new_with_mnemonic (_("_Command Line: "));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox1), label5, FALSE, FALSE, 0);

  cmdline = gtk_entry_new ();
  gtk_widget_show (cmdline);
  gtk_box_pack_start (GTK_BOX (hbox1), cmdline, TRUE, TRUE, 0);
  gtk_entry_set_activates_default (GTK_ENTRY (cmdline), TRUE);

  browse_btn = gtk_button_new ();
  gtk_widget_show (browse_btn);
  gtk_box_pack_start (GTK_BOX (hbox1), browse_btn, FALSE, FALSE, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (browse_btn), alignment1);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox3);

  image1 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox3), image1, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("_Browse"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);

  hbox2 = gtk_hbox_new (FALSE, 32);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox), hbox2, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox2), 4);

  open_in_terminal = gtk_check_button_new_with_mnemonic (_("Opened in Terminal"));
  gtk_box_pack_start (GTK_BOX (hbox2), open_in_terminal, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (open_in_terminal, FALSE);

  set_default = gtk_check_button_new_with_mnemonic (_("Set selected application to default action"));
  gtk_widget_show (set_default);
  gtk_box_pack_start (GTK_BOX (hbox2), set_default, FALSE, FALSE, 0);

  dialog_action_area1 = GTK_DIALOG (app_chooser_dlg)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton);
  gtk_dialog_add_action_widget (GTK_DIALOG (app_chooser_dlg), cancelbutton, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton, GTK_CAN_DEFAULT);

  okbutton = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton);
  gtk_dialog_add_action_widget (GTK_DIALOG (app_chooser_dlg), okbutton, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) notebook, "switch_page",
                            G_CALLBACK (on_notebook_switch_page),
                            GTK_OBJECT (app_chooser_dlg));
  g_signal_connect_swapped ((gpointer) browse_btn, "clicked",
                            G_CALLBACK (on_browse_btn_clicked),
                            GTK_OBJECT (app_chooser_dlg));

  gtk_label_set_mnemonic_widget (GTK_LABEL (label5), cmdline);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (app_chooser_dlg, app_chooser_dlg, "app_chooser_dlg");
  GLADE_HOOKUP_OBJECT_NO_REF (app_chooser_dlg, dialog_vbox, "dialog_vbox");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, label7, "label7");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, file_type, "file_type");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, label4, "label4");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, notebook, "notebook");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, recommended_apps, "recommended_apps");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, label3, "label3");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, all_apps, "all_apps");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, label2, "label2");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, label5, "label5");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, cmdline, "cmdline");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, browse_btn, "browse_btn");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, image1, "image1");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, label6, "label6");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, open_in_terminal, "open_in_terminal");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, set_default, "set_default");
  GLADE_HOOKUP_OBJECT_NO_REF (app_chooser_dlg, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, cancelbutton, "cancelbutton");
  GLADE_HOOKUP_OBJECT (app_chooser_dlg, okbutton, "okbutton");

  gtk_widget_grab_focus (recommended_apps);
  gtk_widget_grab_default (okbutton);
  return app_chooser_dlg;
}

