/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "file-operation.h"
#include "file-operation-ui.h"
#include "glade-support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_fileOperation (void)
{
  GtkWidget *fileOperation;
  GtkWidget *dialog_vbox;
  GtkWidget *table;
  GtkWidget *action;
  GtkWidget *label3;
  GtkWidget *to_label;
  GtkWidget *label4;
  GtkWidget *progress;
  GtkWidget *current;
  GtkWidget *to;
  GtkWidget *from;
  GtkWidget *dialog_action_area;
  GtkWidget *cancel_button;

  fileOperation = gtk_dialog_new ();
  gtk_window_set_default_size (GTK_WINDOW (fileOperation), 400, -1);
  gtk_window_set_type_hint (GTK_WINDOW (fileOperation), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_window_set_gravity (GTK_WINDOW (fileOperation), GDK_GRAVITY_NORTH_EAST);

  dialog_vbox = GTK_DIALOG (fileOperation)->vbox;
  gtk_widget_show (dialog_vbox);

  table = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table);
  gtk_box_pack_start (GTK_BOX (dialog_vbox), table, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table), 4);
  gtk_table_set_col_spacings (GTK_TABLE (table), 4);

  action = gtk_label_new ("");
  gtk_widget_show (action);
  gtk_table_attach (GTK_TABLE (table), action, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (action), 0, 0.5);

  label3 = gtk_label_new (_("Progress: "));
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table), label3, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  /* To: <Destination folder>
ex. Copy file to..., Move file to...etc. */
  to_label = gtk_label_new (_("To: "));
  gtk_widget_show (to_label);
  gtk_table_attach (GTK_TABLE (table), to_label, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (to_label), 0, 0.5);

  /* Processing: <Name of currently proccesed file> */
  label4 = gtk_label_new (_("Processing: "));
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table), label4, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  progress = gtk_progress_bar_new ();
  gtk_widget_show (progress);
  gtk_table_attach (GTK_TABLE (table), progress, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (progress), "0 %");

  /* Preparing to do some file operation (Copy, Move, Delete...)
 */
  current = gtk_label_new (_("Preparing..."));
  gtk_widget_show (current);
  gtk_table_attach (GTK_TABLE (table), current, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (current), 0, 0.5);
  gtk_label_set_ellipsize (GTK_LABEL (current), PANGO_ELLIPSIZE_MIDDLE);

  to = gtk_label_new ("");
  gtk_widget_show (to);
  gtk_table_attach (GTK_TABLE (table), to, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (to), 0, 0.5);

  from = gtk_label_new ("");
  gtk_widget_show (from);
  gtk_table_attach (GTK_TABLE (table), from, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (from), 0, 0.5);

  dialog_action_area = GTK_DIALOG (fileOperation)->action_area;
  gtk_widget_show (dialog_action_area);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area), GTK_BUTTONBOX_END);

  cancel_button = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancel_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (fileOperation), cancel_button, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancel_button, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) cancel_button, "clicked",
                            G_CALLBACK (on_cancel_button_clicked),
                            GTK_OBJECT (fileOperation));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fileOperation, fileOperation, "fileOperation");
  GLADE_HOOKUP_OBJECT_NO_REF (fileOperation, dialog_vbox, "dialog_vbox");
  GLADE_HOOKUP_OBJECT (fileOperation, table, "table");
  GLADE_HOOKUP_OBJECT (fileOperation, action, "action");
  GLADE_HOOKUP_OBJECT (fileOperation, label3, "label3");
  GLADE_HOOKUP_OBJECT (fileOperation, to_label, "to_label");
  GLADE_HOOKUP_OBJECT (fileOperation, label4, "label4");
  GLADE_HOOKUP_OBJECT (fileOperation, progress, "progress");
  GLADE_HOOKUP_OBJECT (fileOperation, current, "current");
  GLADE_HOOKUP_OBJECT (fileOperation, to, "to");
  GLADE_HOOKUP_OBJECT (fileOperation, from, "from");
  GLADE_HOOKUP_OBJECT_NO_REF (fileOperation, dialog_action_area, "dialog_action_area");
  GLADE_HOOKUP_OBJECT (fileOperation, cancel_button, "cancel_button");

  return fileOperation;
}

