/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "file-properties.h"
#include "file-properties-ui.h"
#include "glade-support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_filePropertiesDlg (void)
{
  GtkWidget *filePropertiesDlg;
  GtkWidget *dialog_vbox;
  GtkWidget *notebook;
  GtkWidget *general_table;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label7;
  GtkWidget *mime_type;
  GtkWidget *total_size;
  GtkWidget *mtime;
  GtkWidget *label13;
  GtkWidget *atime;
  GtkWidget *label20;
  GtkWidget *location;
  GtkWidget *file_name;
  GtkWidget *label21;
  GtkWidget *size_on_disk;
  GtkWidget *open_with_label;
  GtkWidget *open_with;
  GtkWidget *label1;
  GtkWidget *vbox1;
  GtkWidget *table3;
  GtkWidget *owner_label;
  GtkWidget *group_label;
  GtkWidget *owner;
  GtkWidget *group;
  GtkWidget *hseparator1;
  GtkWidget *table2;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *owner_r;
  GtkWidget *group_r;
  GtkWidget *others_r;
  GtkWidget *owner_w;
  GtkWidget *group_w;
  GtkWidget *others_w;
  GtkWidget *owner_x;
  GtkWidget *group_x;
  GtkWidget *others_x;
  GtkWidget *set_uid;
  GtkWidget *set_gid;
  GtkWidget *sticky;
  GtkWidget *vseparator1;
  GtkWidget *label2;
  GtkWidget *dialog_action_area;
  GtkWidget *cancel_button;
  GtkWidget *ok_button;

  filePropertiesDlg = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (filePropertiesDlg), _("File Properties"));
  gtk_window_set_position (GTK_WINDOW (filePropertiesDlg), GTK_WIN_POS_CENTER_ON_PARENT);
  gtk_window_set_default_size (GTK_WINDOW (filePropertiesDlg), 360, -1);
  gtk_window_set_type_hint (GTK_WINDOW (filePropertiesDlg), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_window_set_gravity (GTK_WINDOW (filePropertiesDlg), GDK_GRAVITY_CENTER);

  dialog_vbox = GTK_DIALOG (filePropertiesDlg)->vbox;
  gtk_widget_show (dialog_vbox);

  notebook = gtk_notebook_new ();
  gtk_widget_show (notebook);
  gtk_box_pack_start (GTK_BOX (dialog_vbox), notebook, TRUE, TRUE, 0);

  general_table = gtk_table_new (8, 2, FALSE);
  gtk_widget_show (general_table);
  gtk_container_add (GTK_CONTAINER (notebook), general_table);
  gtk_container_set_border_width (GTK_CONTAINER (general_table), 4);
  gtk_table_set_row_spacings (GTK_TABLE (general_table), 4);
  gtk_table_set_col_spacings (GTK_TABLE (general_table), 4);

  label3 = gtk_label_new (_("File Name:"));
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (general_table), label3, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  label4 = gtk_label_new (_("File Type:"));
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (general_table), label4, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  label5 = gtk_label_new (_("Total Size of Files:"));
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (general_table), label5, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  label7 = gtk_label_new (_("Last Modification:"));
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (general_table), label7, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);

  mime_type = gtk_label_new ("");
  gtk_widget_show (mime_type);
  gtk_table_attach (GTK_TABLE (general_table), mime_type, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (mime_type, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (mime_type), TRUE);
  gtk_misc_set_alignment (GTK_MISC (mime_type), 0, 0.5);

  total_size = gtk_label_new ("");
  gtk_widget_show (total_size);
  gtk_table_attach (GTK_TABLE (general_table), total_size, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (total_size, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (total_size), TRUE);
  gtk_misc_set_alignment (GTK_MISC (total_size), 0, 0.5);

  mtime = gtk_label_new ("");
  gtk_widget_show (mtime);
  gtk_table_attach (GTK_TABLE (general_table), mtime, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (mtime, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (mtime), TRUE);
  gtk_misc_set_alignment (GTK_MISC (mtime), 0, 0.5);

  label13 = gtk_label_new (_("Last Access:"));
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (general_table), label13, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);

  atime = gtk_label_new ("");
  gtk_widget_show (atime);
  gtk_table_attach (GTK_TABLE (general_table), atime, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (atime), 0, 0.5);

  label20 = gtk_label_new (_("Location:"));
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (general_table), label20, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  location = gtk_label_new ("");
  gtk_widget_show (location);
  gtk_table_attach (GTK_TABLE (general_table), location, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (location, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (location), TRUE);
  gtk_misc_set_alignment (GTK_MISC (location), 0, 0.5);

  file_name = gtk_entry_new ();
  gtk_widget_show (file_name);
  gtk_table_attach (GTK_TABLE (general_table), file_name, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label21 = gtk_label_new (_("Size on Disk:"));
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (general_table), label21, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  size_on_disk = gtk_label_new ("");
  gtk_widget_show (size_on_disk);
  gtk_table_attach (GTK_TABLE (general_table), size_on_disk, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (size_on_disk, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (size_on_disk), TRUE);
  gtk_misc_set_alignment (GTK_MISC (size_on_disk), 0, 0.5);

  open_with_label = gtk_label_new (_("Open with:"));
  gtk_widget_show (open_with_label);
  gtk_table_attach (GTK_TABLE (general_table), open_with_label, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (open_with_label), 0, 0.5);

  open_with = gtk_combo_box_new_text ();
  gtk_widget_show (open_with);
  gtk_table_attach (GTK_TABLE (general_table), open_with, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label1 = gtk_label_new_with_mnemonic (_("_General"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 0), label1);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (notebook), vbox1);

  table3 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (vbox1), table3, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table3), 2);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 2);

  owner_label = gtk_label_new (_("Owner:"));
  gtk_widget_show (owner_label);
  gtk_table_attach (GTK_TABLE (table3), owner_label, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  group_label = gtk_label_new (_("Group:"));
  gtk_widget_show (group_label);
  gtk_table_attach (GTK_TABLE (table3), group_label, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  owner = gtk_entry_new ();
  gtk_widget_show (owner);
  gtk_table_attach (GTK_TABLE (table3), owner, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  group = gtk_entry_new ();
  gtk_widget_show (group);
  gtk_table_attach (GTK_TABLE (table3), group, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, FALSE, FALSE, 0);

  table2 = gtk_table_new (3, 6, FALSE);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox1), table2, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 2);

  label17 = gtk_label_new (_("Owner:"));
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table2), label17, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  label18 = gtk_label_new (_("Group:"));
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table2), label18, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  label19 = gtk_label_new (_("Other Users:"));
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table2), label19, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  owner_r = gtk_check_button_new_with_mnemonic (_("Read"));
  gtk_widget_show (owner_r);
  gtk_table_attach (GTK_TABLE (table2), owner_r, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (owner_r), 2);

  group_r = gtk_check_button_new_with_mnemonic (_("Read"));
  gtk_widget_show (group_r);
  gtk_table_attach (GTK_TABLE (table2), group_r, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (group_r), 2);

  others_r = gtk_check_button_new_with_mnemonic (_("Read"));
  gtk_widget_show (others_r);
  gtk_table_attach (GTK_TABLE (table2), others_r, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (others_r), 2);

  owner_w = gtk_check_button_new_with_mnemonic (_("Write"));
  gtk_widget_show (owner_w);
  gtk_table_attach (GTK_TABLE (table2), owner_w, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (owner_w), 2);

  group_w = gtk_check_button_new_with_mnemonic (_("Write"));
  gtk_widget_show (group_w);
  gtk_table_attach (GTK_TABLE (table2), group_w, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (group_w), 2);

  others_w = gtk_check_button_new_with_mnemonic (_("Write"));
  gtk_widget_show (others_w);
  gtk_table_attach (GTK_TABLE (table2), others_w, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (others_w), 2);

  owner_x = gtk_check_button_new_with_mnemonic (_("Execute"));
  gtk_widget_show (owner_x);
  gtk_table_attach (GTK_TABLE (table2), owner_x, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (owner_x), 2);

  group_x = gtk_check_button_new_with_mnemonic (_("Execute"));
  gtk_widget_show (group_x);
  gtk_table_attach (GTK_TABLE (table2), group_x, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (group_x), 2);

  others_x = gtk_check_button_new_with_mnemonic (_("Execute"));
  gtk_widget_show (others_x);
  gtk_table_attach (GTK_TABLE (table2), others_x, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (others_x), 2);

  /* This is used in file attribute */
  set_uid = gtk_check_button_new_with_mnemonic (_("Set UID"));
  gtk_widget_show (set_uid);
  gtk_table_attach (GTK_TABLE (table2), set_uid, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (set_uid), 2);

  /* This is used in file attribute */
  set_gid = gtk_check_button_new_with_mnemonic (_("Set GID"));
  gtk_widget_show (set_gid);
  gtk_table_attach (GTK_TABLE (table2), set_gid, 5, 6, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (set_gid), 2);

  /* This is used in file attribute */
  sticky = gtk_check_button_new_with_mnemonic (_("Sticky"));
  gtk_widget_show (sticky);
  gtk_table_attach (GTK_TABLE (table2), sticky, 5, 6, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (sticky), 2);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_table_attach (GTK_TABLE (table2), vseparator1, 4, 5, 0, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 8, 0);

  label2 = gtk_label_new_with_mnemonic (_("_Permissions"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 1), label2);

  dialog_action_area = GTK_DIALOG (filePropertiesDlg)->action_area;
  gtk_widget_show (dialog_action_area);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area), GTK_BUTTONBOX_END);

  cancel_button = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancel_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (filePropertiesDlg), cancel_button, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancel_button, GTK_CAN_DEFAULT);

  ok_button = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (filePropertiesDlg), ok_button, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (ok_button, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) filePropertiesDlg, "response",
                    G_CALLBACK (on_filePropertiesDlg_response),
                    NULL);
  g_signal_connect_swapped ((gpointer) cancel_button, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (filePropertiesDlg));
  g_signal_connect_swapped ((gpointer) ok_button, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (filePropertiesDlg));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filePropertiesDlg, filePropertiesDlg, "filePropertiesDlg");
  GLADE_HOOKUP_OBJECT_NO_REF (filePropertiesDlg, dialog_vbox, "dialog_vbox");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, notebook, "notebook");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, general_table, "general_table");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, label3, "label3");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, label4, "label4");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, label5, "label5");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, label7, "label7");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, mime_type, "mime_type");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, total_size, "total_size");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, mtime, "mtime");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, label13, "label13");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, atime, "atime");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, label20, "label20");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, location, "location");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, file_name, "file_name");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, label21, "label21");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, size_on_disk, "size_on_disk");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, open_with_label, "open_with_label");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, open_with, "open_with");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, label1, "label1");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, table3, "table3");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, owner_label, "owner_label");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, group_label, "group_label");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, owner, "owner");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, group, "group");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, table2, "table2");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, label17, "label17");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, label18, "label18");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, label19, "label19");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, owner_r, "owner_r");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, group_r, "group_r");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, others_r, "others_r");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, owner_w, "owner_w");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, group_w, "group_w");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, others_w, "others_w");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, owner_x, "owner_x");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, group_x, "group_x");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, others_x, "others_x");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, set_uid, "set_uid");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, set_gid, "set_gid");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, sticky, "sticky");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, label2, "label2");
  GLADE_HOOKUP_OBJECT_NO_REF (filePropertiesDlg, dialog_action_area, "dialog_action_area");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, cancel_button, "cancel_button");
  GLADE_HOOKUP_OBJECT (filePropertiesDlg, ok_button, "ok_button");

  return filePropertiesDlg;
}

