/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "pref-dialog.h"
#include "pref-dialog-ui.h"
#include "glade-support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_prefdlg (void)
{
  GtkWidget *prefdlg;
  GtkWidget *dialog_vbox1;
  GtkWidget *notebook1;
  GtkWidget *vbox1;
  GtkWidget *hbox1;
  GtkWidget *label1;
  GtkWidget *filename_encoding;
  GtkWidget *hbox2;
  GtkWidget *label2;
  GtkWidget *bm_open_method;
  GtkWidget *hbox5;
  GtkWidget *label6;
  GtkWidget *theme;
  GtkWidget *show_thumbnail;
  GtkWidget *hbox3;
  GtkWidget *label3;
  GtkObject *max_thumb_size_adj;
  GtkWidget *max_thumb_size;
  GtkWidget *label4;
  GtkWidget *hbox4;
  GtkWidget *label5;
  GtkWidget *terminal;
  GtkWidget *general_tab_label;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton;
  GtkWidget *okbutton;

  prefdlg = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (prefdlg), _("Preference"));
  gtk_window_set_type_hint (GTK_WINDOW (prefdlg), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (prefdlg)->vbox;
  gtk_widget_show (dialog_vbox1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_end (GTK_BOX (dialog_vbox1), notebook1, TRUE, TRUE, 0);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox1);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), vbox1,
                                      FALSE, FALSE, GTK_PACK_START);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 4);

  label1 = gtk_label_new (_("On-disk file name encoding:"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label1), 2, 2);

  filename_encoding = gtk_entry_new ();
  gtk_widget_show (filename_encoding);
  gtk_box_pack_start (GTK_BOX (hbox1), filename_encoding, TRUE, TRUE, 0);
  gtk_widget_set_size_request (filename_encoding, 80, -1);
  gtk_entry_set_max_length (GTK_ENTRY (filename_encoding), 30);

  hbox2 = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox2), 4);

  label2 = gtk_label_new (_("Bookmarks:"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  bm_open_method = gtk_combo_box_new_text ();
  gtk_widget_show (bm_open_method);
  gtk_box_pack_start (GTK_BOX (hbox2), bm_open_method, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (bm_open_method), _("Opened in Current Tab"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (bm_open_method), _("Opened in New Tab"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (bm_open_method), _("Opened in New Window"));

  hbox5 = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox5, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox5), 4);

  label6 = gtk_label_new (_("Icon Theme (Need Restart):"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox5), label6, FALSE, FALSE, 0);

  theme = gtk_combo_box_new_text ();
  gtk_widget_show (theme);
  gtk_box_pack_start (GTK_BOX (hbox5), theme, TRUE, TRUE, 0);

  show_thumbnail = gtk_check_button_new_with_mnemonic (_("Display image files with supported format as thumbnails"));
  gtk_widget_show (show_thumbnail);
  gtk_box_pack_start (GTK_BOX (vbox1), show_thumbnail, FALSE, FALSE, 0);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox3, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox3), 4);

  label3 = gtk_label_new (_("Max size of files displayed as thumbnails:"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  max_thumb_size_adj = gtk_adjustment_new (0, 0, 32768, 1, 10, 10);
  max_thumb_size = gtk_spin_button_new (GTK_ADJUSTMENT (max_thumb_size_adj), 1, 0);
  gtk_widget_show (max_thumb_size);
  gtk_box_pack_start (GTK_BOX (hbox3), max_thumb_size, TRUE, TRUE, 0);

  label4 = gtk_label_new ("KB");
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label4), 2, 0);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox4, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox4), 4);

  label5 = gtk_label_new (_("Terminal:"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  terminal = gtk_combo_box_entry_new_text ();
  gtk_widget_show (terminal);
  gtk_box_pack_start (GTK_BOX (hbox4), terminal, TRUE, TRUE, 0);

  general_tab_label = gtk_label_new_with_mnemonic (_("_General"));
  gtk_widget_show (general_tab_label);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), general_tab_label);

  dialog_action_area1 = GTK_DIALOG (prefdlg)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton);
  gtk_dialog_add_action_widget (GTK_DIALOG (prefdlg), cancelbutton, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton, GTK_CAN_DEFAULT);

  okbutton = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton);
  gtk_dialog_add_action_widget (GTK_DIALOG (prefdlg), okbutton, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (prefdlg, prefdlg, "prefdlg");
  GLADE_HOOKUP_OBJECT_NO_REF (prefdlg, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (prefdlg, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (prefdlg, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (prefdlg, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (prefdlg, label1, "label1");
  GLADE_HOOKUP_OBJECT (prefdlg, filename_encoding, "filename_encoding");
  GLADE_HOOKUP_OBJECT (prefdlg, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (prefdlg, label2, "label2");
  GLADE_HOOKUP_OBJECT (prefdlg, bm_open_method, "bm_open_method");
  GLADE_HOOKUP_OBJECT (prefdlg, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (prefdlg, label6, "label6");
  GLADE_HOOKUP_OBJECT (prefdlg, theme, "theme");
  GLADE_HOOKUP_OBJECT (prefdlg, show_thumbnail, "show_thumbnail");
  GLADE_HOOKUP_OBJECT (prefdlg, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (prefdlg, label3, "label3");
  GLADE_HOOKUP_OBJECT (prefdlg, max_thumb_size, "max_thumb_size");
  GLADE_HOOKUP_OBJECT (prefdlg, label4, "label4");
  GLADE_HOOKUP_OBJECT (prefdlg, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (prefdlg, label5, "label5");
  GLADE_HOOKUP_OBJECT (prefdlg, terminal, "terminal");
  GLADE_HOOKUP_OBJECT (prefdlg, general_tab_label, "general_tab_label");
  GLADE_HOOKUP_OBJECT_NO_REF (prefdlg, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (prefdlg, cancelbutton, "cancelbutton");
  GLADE_HOOKUP_OBJECT (prefdlg, okbutton, "okbutton");

  gtk_widget_grab_default (okbutton);
  return prefdlg;
}

