.TH PCMANFM 1 "February 13, 2012"
.SH NAME
pcmanfm \- lightweight file manager based on GTK+.
.SH SYNOPSIS
.B pcmanfm
[\fIOPTION\fR]... [\fIFILE\fR]...
.SH OPTIONS
.TP
.B \-p, \-\-profile=<profile>
Use settings from <profile>
.TP
.B \-d, \-\-daemon-mode
Run PCManFM as a daemon
.TP
.B \-\-no\-desktop
No function. Just to be compatible with nautilus
.TP
.B \-\-desktop
Launch desktop manager
.TP
.B \-\-desktop\-off
Turn off desktop manager if it's already running
.TP
.B \-\-desktop\-pref
Open desktop preferences dialog
.TP
.B \-w, \-\-set\-wallpaper=<file>
Set desktop wallpaper
.TP
.B \-\-wallpaper\-mode={color,stretch,fit,center,tile}
Set wallpaper mode
.TP
.B \-\-show\-pref=n
Open preferences dialog at n-th page
.TP
.B \-\-display=DISPLAY
X display to use
.TP
.B \-h, \-\-help
Show summary of options.
.SH AUTHOR
pcmanfm was written by Hong Jen Yee <pcman.tw@gmail.com>.
.PP
This manual page was written by Sergey Slipchenko <faergeek@gmail.com>,
for the Debian project (and may be used by others).
